baseURL = 'https://reflections.accapehart.com/'
languageCode = 'en-us'
title = 'Reflections on Quotes'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "AC Capehart"
  description = "These quotes have been meaningful to me, so I'm delighed to share them and my reflections on them with you."
  github = "capehart"
  twitter = "capehart"
  linkedin = "accapehart"
  email = "reflections@accapehart.com"
  url = "https://reflections.accapehart.com"
  keywords = "quotes, reflections"
  rss = true
  lastmod = true
  userStatusEmoji = "ðŸ˜€"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/wisdom-icon.svg"
  location = "Virginia, USA"
  enableGitalk = false
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

